/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { AssignmentManager } from '../../jupyter/assignments';
import { ProxiedJupyterClient } from '../../jupyter/client';
import {
  DEFAULT_NOTEBOOK_EXECUTION_TIMEOUT_MS,
  DEFAULT_RUNTIME_HF_CACHE_TOKEN_PATH,
  DEFAULT_RUNTIME_HF_HOME_TOKEN_PATH,
  DEFAULT_RUNTIME_HF_STARTUP_PATH,
  DEFAULT_RUNTIME_HF_TOKEN_PATH,
} from './constants';
import { RuntimeSecretsSyncArgs, RuntimeSecretsSyncResult } from './types';
import { ensureFreshRuntimeConnection } from './runtime-connection';
import { selectExecutionServer, toRuntimeRecord } from './runtime-selection';
import { writeTextFileToRuntime } from './runtime-files';
import {
  executeCodeOnKernel,
  makeSessionName,
  resolveKernelName,
} from './execution/kernel-channel';
import { log } from '../../common/logging';

function buildHfStartupScript(runtimeTokenPath: string): string {
  const tokenPath = JSON.stringify(runtimeTokenPath);
  return [
    '# Auto-generated by Colab agent bridge.',
    'import os',
    'from pathlib import Path',
    `_TOKEN_PATH = Path(${tokenPath})`,
    'if _TOKEN_PATH.exists():',
    '    _token = _TOKEN_PATH.read_text(encoding="utf-8").strip()',
    '    if _token:',
    '        os.environ.setdefault("HF_TOKEN", _token)',
    '        os.environ.setdefault("HF_ACCESS_TOKEN", _token)',
    '        os.environ.setdefault("HUGGINGFACE_HUB_TOKEN", _token)',
    '        os.environ.setdefault("HUGGINGFACEHUB_API_TOKEN", _token)',
    '',
  ].join('\n');
}

export async function runtimeSecretsSync(
  assignmentManager: AssignmentManager,
  rawArgs: RuntimeSecretsSyncArgs,
): Promise<RuntimeSecretsSyncResult> {
  let runtime = await selectExecutionServer(
    assignmentManager,
    rawArgs,
    'runtime.secrets.sync',
  );
  runtime = await ensureFreshRuntimeConnection(assignmentManager, runtime);
  const runtimeRecord = toRuntimeRecord(runtime);
  let client = ProxiedJupyterClient.withStaticConnection(runtime);
  const wrotePaths: string[] = [];

  await writeTextFileToRuntime(
    client,
    DEFAULT_RUNTIME_HF_TOKEN_PATH,
    `${rawArgs.hfToken}\n`,
    true,
  );
  wrotePaths.push(DEFAULT_RUNTIME_HF_TOKEN_PATH);

  if (rawArgs.writeHfHomeTokenFile ?? true) {
    await writeTextFileToRuntime(
      client,
      DEFAULT_RUNTIME_HF_HOME_TOKEN_PATH,
      `${rawArgs.hfToken}\n`,
      true,
    );
    wrotePaths.push(DEFAULT_RUNTIME_HF_HOME_TOKEN_PATH);
  }

  if (rawArgs.writeHfCacheTokenFile ?? true) {
    await writeTextFileToRuntime(
      client,
      DEFAULT_RUNTIME_HF_CACHE_TOKEN_PATH,
      `${rawArgs.hfToken}\n`,
      true,
    );
    wrotePaths.push(DEFAULT_RUNTIME_HF_CACHE_TOKEN_PATH);
  }

  if (rawArgs.writeIpythonStartup ?? true) {
    await writeTextFileToRuntime(
      client,
      DEFAULT_RUNTIME_HF_STARTUP_PATH,
      buildHfStartupScript(DEFAULT_RUNTIME_HF_TOKEN_PATH),
      true,
    );
    wrotePaths.push(DEFAULT_RUNTIME_HF_STARTUP_PATH);
  }

  const verifyRuntimeEnv = rawArgs.verifyRuntimeEnv ?? true;
  let hfTokenVisibleInNewKernel: boolean | undefined;
  if (verifyRuntimeEnv) {
    runtime = await ensureFreshRuntimeConnection(assignmentManager, runtime);
    client = ProxiedJupyterClient.withStaticConnection(runtime);
    const kernelName = await resolveKernelName(client);
    const sessionName = makeSessionName();
    const sessionPath = `agent/${sessionName}.ipynb`;
    const session = await client.sessions.create({
      session: {
        name: sessionName,
        path: sessionPath,
        type: 'notebook',
        kernel: { name: kernelName } as unknown as { id: string; name: string },
      },
    });

    if (!session.id || !session.kernel?.id) {
      throw new Error('Failed to create verification session for secret sync.');
    }

    try {
      runtime = await ensureFreshRuntimeConnection(assignmentManager, runtime);
      const verify = await executeCodeOnKernel(
        runtime,
        session.kernel.id,
        [
          'import os',
          'print("HF_TOKEN_VISIBLE", bool(os.environ.get("HF_TOKEN")))',
        ].join('\n'),
        DEFAULT_NOTEBOOK_EXECUTION_TIMEOUT_MS,
      );
      const outputText = verify.outputs
        .filter((output) => output.type === 'stream' && typeof output.text === 'string')
        .map((output) => output.text)
        .join('\n');
      hfTokenVisibleInNewKernel = outputText.includes('HF_TOKEN_VISIBLE True');
    } finally {
      try {
        runtime = await ensureFreshRuntimeConnection(assignmentManager, runtime);
        client = ProxiedJupyterClient.withStaticConnection(runtime);
        await client.sessions.delete({ session: session.id });
      } catch (error) {
        log.warn(
          `Failed cleaning up notebook session ${session.id} after runtime.secrets.sync verification.`,
          error,
        );
      }
    }
  }

  return {
    runtime: runtimeRecord,
    wrotePaths,
    verifyRuntimeEnv,
    hfTokenVisibleInNewKernel,
  };
}
